/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as ContainerImport } from './pages/container'

// Create Virtual Routes

const ListGroupLazyImport = createFileRoute('/list-group')()
const ButtonsLazyImport = createFileRoute('/buttons')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ListGroupLazyRoute = ListGroupLazyImport.update({
  path: '/list-group',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/list-group.lazy').then((d) => d.Route))

const ButtonsLazyRoute = ButtonsLazyImport.update({
  path: '/buttons',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/buttons.lazy').then((d) => d.Route))

const ContainerRoute = ContainerImport.update({
  path: '/container',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/container': {
      preLoaderRoute: typeof ContainerImport
      parentRoute: typeof rootRoute
    }
    '/buttons': {
      preLoaderRoute: typeof ButtonsLazyImport
      parentRoute: typeof rootRoute
    }
    '/list-group': {
      preLoaderRoute: typeof ListGroupLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  ContainerRoute,
  ButtonsLazyRoute,
  ListGroupLazyRoute,
])

/* prettier-ignore-end */
