printWidth: 110
singleQuote: true
jsxSingleQuote: true
useTabs: false
semi: false
trailingComma: es5
plugins:
  - tailwindcss

overrides:
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      parser: yaml
      plugins:
        - '@prettier/plugin-xml'
      xmlSelfClosingSpace: true
      xmlSortAttributesByKey: true
