allowBuilds:
  '@swc/core': true
  esbuild: true
  msw: false
  nx: true
minimumReleaseAgeExclude:
  - prettier@3.9.1
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - nx
